### ISSUE TITLE
[RFD] Dropdown Menu

### ISSUE THREAD

**Issue by korbinancell** [Faithlife/styled-ui#141]
# Dropdown

* Specifically describe the problem you'd like the new component to solve:

Dropdowns are a common ui element and there are many inconsistent implementations of them even in single projects.

* Are there existing solutions or examples where this component would help?

The `Popover` component here has much of the functionality that we would want.

* Describe the proposed API:

\- A top level `Dropdown` component that would wrap the `DropdownToggle` and `DropdownMenu`. It would include a optional `isOpen` prop to allow the dropdown to be controlled or not. A `onClickAway` prop that would serve as a callback after the dropdown has lost focus. 
\- A `DropdownToggle` that would pass a toggle function to its child using a render prop pattern.
\- A `DropdownMenu` that will accept the same props as a `Popover` but with the additional `childrenTheme` property on theme that will provide a theme to every `DropdownItem`.
\- A `DropdownItem` this will accept a onClick handler as well as a theme prop.

![image](https://user-images.githubusercontent.com/14059089/53523871-d3873300-3a92-11e9-8a1f-f14c68eab627.png)

* Are there existing specs or designs?

There are many implementations of dropdowns currently in Flcom and Giving.
Here is what I used as the basic spec https://app.zeplin.io/project/58a23c2d4597afb248c13a43/screen/59ee876e4582a457c39dbefe

* Do you have additional questions?
n/a

**Comment by bryanrsmith** [comment]
Questions & comments:

1. Does `DropdownMenu` accept other children? What if the dropdown needs a header, or filter input, or named sections, or menu separators?
1. What about non-button menu items? Checkbox-style menu items are common, and clicking them usually doesn't cause the menu to close.
1. Should we consider making `Dropdown` a controlled input rather than exposing the callback through the `DropdownToggle`? This would make the component more flexible by easily allowing consumers to make the dropdown initially open, or toggle the dropdown from an external source, or decide whether or not the dropdown should remain open when a menu item is clicked.
1. I don't understand the theming strategy. Sounds like the menu passes childrenTheme to menu items? How does that relate to the theme prop accepted by menu items? Is this passed via context instead of being a prop, or are we using cloneElement to inject it?
1. How does `DropdownMenu` avoid overflowing containers? It seems like we'd need an API for helping it avoid collisions with the edge of the screen and without obscuring the toggle button. Does `DropdownToggle` render a container element that we can use as a reference point, or should we add an API for passing a ref down to the trigger element?

**Comment by korbinancell** [comment]
Here is a possible starting point for better handling focusing https://github.com/okonet/react-simple-focus-within

**Comment by bryanrsmith** [comment]
Also relevant: https://github.com/reactjs/rfcs/pull/109

**Comment by korbinancell** [comment]
@bryanrsmith 
> 1\. Does `DropdownMenu` accept other children?

My first thought would be no. I think if you want a drop down list then use the dropdown, otherwise use a popover. But I could the use case for allowing more.

>  2\. What about non-button menu items?

That would be easy enough to add and would probably fit in the definition above.

> 3\. Should we consider making `Dropdown` a controlled input

I would argue for, at the very least, allowing for the consumer to choose. If you supply a `isOpen` prop then it will default to that, otherwise it will just be a drop in component that handles its own state.

> 4\. I don't understand the theming strategy.

My thought was that we allow the dropdown menu to pass the same theme to all of its children. Then if you want to specifically override the theme for a specific child you may using a 'localTheme' prop. styled-components has a `ThemeProvider` component that passes the theme through context.

> 5\. How does `DropdownMenu` avoid overflowing containers?

The `DropdownMenu` is based on the `Popover` which uses [popper.js](https://popper.js.org/) to handle positioning and the reference point.

**Comment by bryanrsmith** [comment]
> My first thought would be no. I think if you want a drop down list then use the dropdown, otherwise use a popover. But I could the use case for allowing more.

This may lead to a proliferation of menu item components that may or may not be relevant to any particular consumer. One possibility is to provide a set of components that are both small and likely to be relevant to a wide range of consumers, but also allow other children to be rendered into the dropdown. That makes the default experience smooth, while allowing consumer flexibility.

> I would argue for, at the very least, allowing for the consumer to choose. If you supply a isOpen prop then it will default to that, otherwise it will just be a drop in component that handles its own state.

I would strongly prefer to support only a single API. Multiple mechanisms for accomplishing the same thing complicates implementations and drastically increases the surface area required for testing. Since controlled inputs are generally more flexible, that would be my preference.

> Then if you want to specifically override the theme for a specific child you may using a 'localTheme' prop. styled-components has a ThemeProvider component that passes the theme through context.

My concern with this is that it exposes the internal styling implementation to consumers. Once we start allowing the whole theme object to be overridden, almost any styling change is potentially breaking. It'd be safer to add specific props to the menu item components, or allow consumers to render their own custom menu items.

> The DropdownMenu is based on the Popover which uses popper.js to handle positioning and the reference point.

Sounds good, but what's the mechanism for providing popper with the reference element?

**Comment by korbinancell** [comment]
> My concern with this is that itexposes the internal styling implementation to consumers

Almost every new component exposes a 'theme' prop. It will default to the consumer provided theme or if it is not provided, to a preset default.

https://github.com/Faithlife/styled-ui/blob/master/components/button/styled.jsx#L76

> what's the mechanism for providing popper with the reference element?

It is handled by the `PopoverReference` component.

https://github.com/Faithlife/styled-ui/blob/master/components/popover/popper-helpers.jsx#L10

**Comment by korbinancell** [comment]
Closing with the merge of https://github.com/Faithlife/styled-ui/pull/154
