### ISSUE TITLE
Text Input won't display falsy values

### ISSUE THREAD

**Issue by RobertBolender** [Faithlife/styled-ui#236]
I tried to display the value `0` in an Input element, but we're checking whether it's falsy:

https://github.com/Faithlife/styled-ui/blob/28d2bd58b1dce44e09e3c9c41e5a104531cedf62/components/input/component.jsx#L83

Am I missing a good reason to have that falsy check?

**Comment by bryanrsmith** [comment]
Guessing, but React warns when you change an input between controlled and uncontrolled. I assume the purpose of this check is to make the input more forgiving to consumers that would otherwise have to ensure they weren't passing null/undefined. We can't remove the check without potentially breaking consumers, but restricting it to strictly `null` and `undefined` seems reasonable to me to fix the `type="number"` use case.

**Comment by bryanrsmith** [comment]
The file preview in this issue is cool! I haven't seen that before.

**Comment by RobertBolender** [comment]
So the suggestion I'm hearing is to update this line to:

`value={(value !== null || value !== undefined) ? value || ''}`

Does that look right?

**Comment by bryanrsmith** [comment]
~That doesn't seem right.~ Sneaky ;-)

**Comment by bryanrsmith** [comment]
`value={(value !== null && value !== undefined) ? value : ''}`, probably.
