### ISSUE TITLE
Inferred input tooltips don't work on mobile (by current design)

### ISSUE THREAD

**Issue by kylebeede** [Faithlife/styled-ui#239]
It's conditionally rendered [here](https://github.com/Faithlife/styled-ui/blob/1bf2d2486dcf943e5fee8b90bb87039b80017ff2/components/popover/tooltip.jsx#L31-L47). Seems like we could use that same `isMobile` logic to update the click handler on mobile to show the tooltip on the first click and confirm on the second click.

**Comment by RobertBolender** [comment]
@kylebeede, @bryankenote, have there been any recent design specs or discussions on this in the ChMS space?

I found this [discussion in Flowdock from January](https://www.flowdock.com/app/logos/styled-ui/threads/ZpWBkoArT7gWWXa4pfSZ5_t_s1q) where the conclusion was that anchoring popovers to *non-interactive* icons would not be a problem, but adding them to *interactive* buttons would still be undesirable.

**Comment by bryankenote** [comment]
The last I heard was the feedback on my pr. I haven't heard anything new since then. @sportnak Anything new here?

**Comment by sportnak** [comment]
This is honestly more of a design question - we have a button that accepts inferred info. So the following questions would need to be addressed:
1. Do people misunderstand the inferred button or click it unexpectedly?
2. Should we change the icon so that it's more clear that an action will happen if you click it and what that action is?
3. Should we move the interaction into the popover? One click to open the popover and one click in the popover?

I'm not sure these are questions I'm well equipped to answer. Can we ping a UI/UX person for this?

**Comment by RobertBolender** [comment]
> I'm not sure these are questions I'm well equipped to answer. Can we ping a UI/UX person for this?

I will ping UI/UX on this, I was just asking here first in case that question had already been asked of them and answered elsewhere.

**Comment by tywmick** [comment]
Was this more or less resolved by 789e5b45c8af4452a2d4e20aad55de757f69092c, which added the `toggleOnClick` prop? You have to enable it explicitly (as opposed to always enabling it on mobile), but that's the functionality that's desired, right?

**Comment by RobertBolender** [comment]
Sure enough! That's enough evidence for me to consider this issue resolved.
If any interested parties disagree, feel free to re-open this issue or create a new one.
