### ISSUE TITLE
Issues with ellipsizing text in help box contents

### ISSUE THREAD

**Issue by SethCopeland** [Faithlife/styled-ui#279]
I was having issues getting text to ellipsize when overflowed correctly on the content of a HelpBox.

If I set `min-width: 0` on this style [here](https://github.com/Faithlife/styled-ui/blob/master/components/help-box/styled.jsx#L48) in dev-tools it works.

Would it be reasonable to add `min-width: 0` to that style or expose a class name property to override it?

**Comment by tywmick** [comment]
Hope you don't mind me resurrecting an old issue, but is this more or less what you were trying to do?

<img width="795" alt="Ellipsis bug inside HelpBox.Body" src="https://user-images.githubusercontent.com/5317080/99857128-901f0300-2b58-11eb-8097-c0927f72b463.png">

I found I had to do two things to fix that:

1. Add `min-width: 0` to [`HelpBoxContent`](https://github.com/Faithlife/styled-ui/blob/6043ef87d8d5df05f63915ac24c668abdf22c98f/components/help-box/styled.jsx#L48), as you pointed out. That reined in the width of the `HelpBox.Body` `div` so the `div` itself wouldn't overflow its container.
2. Remove [`display: flex` from `HelpBoxBody`](https://github.com/Faithlife/styled-ui/blob/6043ef87d8d5df05f63915ac24c668abdf22c98f/components/help-box/styled.jsx#L67). With `display: flex`, `overflow: hidden`, and `white-space: nowrap` all set on the `HelpBox.Body` `div`, even though the width of the `div` itself was limited, the text children still overflowed outside its `div` container.
   - And don't _think_ `HelpBox.Body` needs to be a flex container by default, since all the examples in the catalog only use text children inside that component. But let me know if that isn't the case. 👍🏼

Here's how it looks for me after those two changes:

<img width="796" alt="Ellipsis fixed inside HelpBox.Body" src="https://user-images.githubusercontent.com/5317080/99858773-43d5c200-2b5c-11eb-90a6-713258dc9929.png">

-----

On the other hand, if you were trying to ellipsize some text directly inside a `HelpBox`, like

```jsx
<HelpBox style={{
	overflow: "hidden",
	whiteSpace: "nowrap",
	textOverflow: "ellipsis",
}}>
	This is a really really really really really really really really really
	really really really really really really really really really long alert.
</HelpBox>
```

...I wasn't able to find a CSS solution that let `HelpBoxContent` continue being a flex container, so fixing this situation may require checking if `HelpBox`'s `children` is just a string and automatically placing it inside a `HelpBox.Body` if it is.

-----

Should I go ahead and start a PR for the `HelpBox.Body` situation, at least?

**Comment by RobertBolender** [comment]
Some Helpboxes allow for multiple lines of text, so adding `whitespace:nowrap` would be incorrect.
We can look at this again if this comes up again, but otherwise I expect that styled-system props will allow these to be configurable on a case-by-case basis to match our specs.
