### ISSUE TITLE
[BUG] validate prop used inconsistently in date-picker-input

### ISSUE THREAD

**Issue by rmjohnson** [Faithlife/styled-ui#401]
**Describe the bug**
In [one case](https://github.com/Faithlife/styled-ui/blob/c6a629f1453e323529e98c5fd911d93dc6ac6ea3/components/date-picker-input/component.jsx#L76) we assume a lack of a `validate` prop means all dates are valid. However, it *looks* like [in this case](https://github.com/Faithlife/styled-ui/blob/c6a629f1453e323529e98c5fd911d93dc6ac6ea3/components/date-picker-input/component.jsx#L88) we assume a lack of a `validate` prop means no dates are valid. These should be consistent.

**Comment by rmjohnson** [comment]
This feels like a *great* thing to do a jest test for. :wink: @RobertBolender @korbinancell

**Comment by tywmick** [comment]
Have a preference for which direction to go with this, whether `validate` should be required or not? I can go update #392 accordingly. 👌🏼

I'm assuming _not_ required is the preference, since its prop type isn't required...

https://github.com/Faithlife/styled-ui/blob/c6a629f1453e323529e98c5fd911d93dc6ac6ea3/components/date-picker-input/component.jsx#L190

...and `DatePicker` doesn't require it, either...

https://github.com/Faithlife/styled-ui/blob/c6a629f1453e323529e98c5fd911d93dc6ac6ea3/components/date-picker/calendar-date/component.jsx#L41-L43

https://github.com/Faithlife/styled-ui/blob/c6a629f1453e323529e98c5fd911d93dc6ac6ea3/components/date-picker/calendar-date/component.jsx#L60-L62

https://github.com/Faithlife/styled-ui/blob/c6a629f1453e323529e98c5fd911d93dc6ac6ea3/components/date-picker/calendar-date/component.jsx#L95

...but I just want to make sure first.

**Comment by rmjohnson** [comment]
I agree with your assessment, thanks @tywmick !

**Comment by tywmick** [comment]
Right on! I've added the fix to both the v5 and v6 `DatePickerInput`s in #392.

### Original:

https://github.com/Faithlife/styled-ui/blob/c6a629f1453e323529e98c5fd911d93dc6ac6ea3/components/date-picker-input/component.jsx#L88-L93

### Update:

```js
if (!validate || validate(selectedDate)) {
	setCurrentDate(selectedDate);
	setText(null);
	setIsPopoverOpen(false);
	onChange(selectedDate);
}
```

I didn't set that PR to close this one, though, since there's still the [need for testing](https://github.com/Faithlife/styled-ui/issues/401#issuecomment-738868556). 👍🏼

**Comment by RobertBolender** [comment]
The bug portion of this issue was resolved, so I will mark it as such.
We know we need tests, and I don't feel that we need this open issue to remind us.
