### ISSUE TITLE
Tooltip closes when mouse moves over tooltip content itself

### ISSUE THREAD

**Issue by tywmick** [Faithlife/styled-ui#467]
### _Original description under the title "Add `delay` prop to v6 `Popover`":_

Not crucial, but the v5 `Popover` had a [`delay` prop](https://github.com/Faithlife/styled-ui/blob/e75309a44de6eac24c1b9aeef30790eac02014b1/components/popover/popover-base.jsx#L47-L48) that allowed the consumer to specify numbers of milliseconds to delay showing and/or hiding the popover. I'm having to lose this feature as I'm updating Tasks to Styled UI v6 ([Tasks#187](https://git.faithlife.dev/Logos/Tasks/pull/187)).

It looks like `Tooltip` still has a built-in 200ms delay, using a `useDebouncedCallback` hook, so it would probably be fairly simple to adapt that pattern for the new `Popover`:

https://github.com/Faithlife/styled-ui/blob/5dfe1dfcaa866f2309c08a53980b01cda5230bc8/components/popover/tooltip.jsx#L14-L26

**Comment by EthanRutherford** [comment]
The new popover is "lower level" than the old one. The consumer controls how and when to show the popover, and can achieve a delay by simply debouncing their own show/hide state transitions.

However, I'd also question what use case there is for a popover with a delayed open, other than a tooltip? If the user clicks a button to open the popover, it should be immediate.

From reading your comment in the linked tasks PR, it sounds like what you really are after *is* a tooltip, it's just that if the mouse enters the tooltip content itself, the tooltip closes. 
I might opine that that's actually a bugfix/improvement to tooltips that we should make, rather than adding any state management to popovers.

**Comment by tywmick** [comment]
Excellent analysis, that's a much better solution! Should I create a new issue and close this one or just change the title of this issue?

**Comment by EthanRutherford** [comment]
IMO, you can keep this one and change the title. Don't know if @RobertBolender has a different opinion, though.

**Comment by RobertBolender** [comment]
To ensure I'm understanding the updated recommendation: We want to add a `delay` prop to the `Tooltip` component, rather than to `Popovers`? No objection to renaming and re-using this issue 👍

**Comment by EthanRutherford** [comment]
Almost. `Tooltip` already has a built-in delay, but it's not configurable. Making it configurable could be done as well, but the key issue is that currently, a `Tooltip` opens when the reference is hovered, and closes when the reference is no longer hovered. What we'd like to do is make it so that hovering the `Tooltip` *content* will also keep the tooltip open. Currently, since you `mouseOut` of the reference, it will close if you move the mouse over the tooltip content.

**Comment by tywmick** [comment]
Would we want to make this behavior itself optional? Not sure which should be the default, but I can see a situation in which you wouldn't want mousing over the tooltip content to keep it open, when the tooltip doesn't have anything interactive on it. Like if it's just explaining an acronym or acting as an inline footnote or something.

At the same time, I've been frustrated before by not being able to copy text on tooltips because they disappear as soon as I try, so if I can only choose one behavior, I'd pick staying open when moving the mouse over the tooltip content.
